### ISSUE TITLE
获取shareid, uk, fsidlist失败，错误码：9019

### ISSUE THREAD

**Issue by freezy2000** [iyzyi/BaiduYunTransfer#5]
最近出现的问题，错位代码：9019，在文档中没查到错误原因。

asscee_token: 121.5724b0ab51f421a7c1cccd7099112e41.Ys0ggfHTjqfL2Bm8IpJzBRG47YO-ZX_Erd6UbMQ.FrptHA
refresh_token: 122.cb34322345cce9fbceb61c519e253af.YB3qoT-PPlAIOya81AT81b9ZDNfqRejA_vgkbkQ.eVfdog
short_link: https://pan.baidu.com/s/1VAFBpm8XuntFn5EjS81O3g
long_link: /share/init?surl=VAFBpm8XuntFn5EjS81O3g
surl: VAFBpm8XuntFn5EjS81O3g
sekey: cTswybvheeXIcQw6bxH19sQnzj9UwJncMc21wrRLRbA=
获取shareid, uk, fsidlist失败，错误码：9019，错误未知，请尝试查询https://pan.baidu.com/union/document/error#%E9%94%99%E8%AF%AF%E7%A0%81%E5%88%97%E8%A1%A8

**Comment by luo0427** [comment]
@freezy2000 错误码：9019 这个问题解决了嘛？
我最近也遇到了相同的问题，无奈呀。

**Comment by luo0427** [comment]
![image](https://user-images.githubusercontent.com/38783151/199192196-a827e579-0692-44f0-8015-a929d97b228e.png)
问题找到了，是百度网盘接口的问题。。。

**Comment by iyzyi** [comment]
> @freezy2000 错误码：9019 这个问题解决了嘛？ 我最近也遇到了相同的问题，无奈呀。

我此前没有回复[freezy2000]的issue是因为他的分享链接是无效的，转存失败是可预见的。你的分享链接确定是有效的吗？（另：客服的回复好像是敷衍的套话）

**Comment by luo0427** [comment]
> > @freezy2000 错误码：9019 这个问题解决了嘛？ 我最近也遇到了相同的问题，无奈呀。
> 
> 我此前没有回复[freezy2000]的issue是因为他的分享链接是无效的，转存失败是可预见的。你的分享链接确定是有效的吗？（另：客服的回复好像是敷衍的套话）

这个问题我以前也遇到过，后来它自个就恢复了。我也没修改任务代码。今天又出现了这个问题，昨天跟今天早上都好好的，下午就不行了。你也可以试试。下面这个分享应该是没问题的，我用网页测试过的，没有失效的。
https://pan.baidu.com/s/1RyxZ43mHcXKMWeANrZvx2A
4L26
客服敷衍这个也没啥招，毕竟开放平台文档里面也写了，分享的接口对个人已经下线了。直接跟客户说分享里面的转存接口有问题。分享接口已经停止维护了。

**Comment by luo0427** [comment]
![image](https://user-images.githubusercontent.com/38783151/199439332-d2111d5d-f4c6-45d2-b5c5-ba6ac945c9a1.png)
加上 access_token 参数好了

**Comment by freezy2000** [comment]
> > > @freezy2000 错误码：9019 这个问题解决了嘛？ 我最近也遇到了相同的问题，无奈呀。
> > 
> > 
> > 我此前没有回复[freezy2000]的issue是因为他的分享链接是无效的，转存失败是可预见的。你的分享链接确定是有效的吗？（另：客服的回复好像是敷衍的套话）
> 
> 这个问题我以前也遇到过，后来它自个就恢复了。我也没修改任务代码。今天又出现了这个问题，昨天跟今天早上都好好的，下午就不行了。你也可以试试。下面这个分享应该是没问题的，我用网页测试过的，没有失效的。 https://pan.baidu.com/s/1RyxZ43mHcXKMWeANrZvx2A 4L26 客服敷衍这个也没啥招，毕竟开放平台文档里面也写了，分享的接口对个人已经下线了。直接跟客户说分享里面的转存接口有问题。分享接口已经停止维护了。

我提问的当天就给百度提交了问题反馈，第二天回复邮件，已经解决了。我当时测试也的确是解决了。

**Comment by UVJkiNTQ** [comment]
@freezy2000 @luo0427 我试着加了下access_token依旧提示9019。
最近有使用过吗？

        url = 'https://pan.baidu.com/rest/2.0/xpan/share?method=verify'
        params = {'access_token': self.access_token, 'surl': self.surl}

**Comment by iyzyi** [comment]
> @freezy2000 @luo0427 我试着加了下access_token依旧提示9019。 最近有使用过吗？
> 
> ```
>     url = 'https://pan.baidu.com/rest/2.0/xpan/share?method=verify'
>     params = {'access_token': self.access_token, 'surl': self.surl}
> ```

刚刚修复了，现在再试下吧
