### ISSUE TITLE
获取sekey失败，错误码：9019，错误未知

### ISSUE THREAD

**Issue by UVJkiNTQ** [iyzyi/BaiduYunTransfer#7]
有一阵子没用了，最近提示这个错误:
获取sekey失败，错误码：9019，错误未知

去看了眼文档，这是不是官方新加的限制？

名称 | 类型 | 必需 | 示例 | 参数位置 | 描述
-- | -- | -- | -- | -- | --
pwd | string | 是 | abcd | body | 访问密码
third_type | int | 是 | 9999 | body | 第三方标识
redirect | int | 是 | 0 | body | 是否直接跳转到内容页

**Comment by UVJkiNTQ** [comment]
#5

**Comment by iyzyi** [comment]
已修复
